notes
yetanalytics/moodle-logstore_xapi pull request #52
Opened 2024-11-04 19:56 UTC by invaliduser

adds `note_created`, `note_updated`, `notes_viewed` events

2024-11-11 17:01 UTC, milt commented on src/transformer/events/core/note_created.php
> +  }
it's a little weird to keep the generic debug code in here, if you look at our other events we generally name things a little better so they are comprehensible later on. the event object is a note, call it that. The whole if construct is superfluous if you know what event you are working with.

2024-11-11 17:01 UTC, milt commented on src/transformer/events/core/note_created.php
> +                                 : $repo->read_record_by_id("course",1)));
same stuff about lang as before, use course and fall back to source

2024-11-11 17:02 UTC, milt commented on src/transformer/events/core/note_created.php
> +               'display' => ['en' => 'Created']
why are you hardcoding lang

2024-11-11 17:02 UTC, milt commented on src/transformer/events/core/note_updated.php
> +    }
see https://github.com/yetanalytics/moodle-logstore_xapi/pull/52/files#r1836969306

2024-11-11 17:02 UTC, milt commented on src/transformer/events/core/note_updated.php
> +                   'display' => ['en' => 'Updated']
hardcoded lang

2024-11-11 17:03 UTC, milt commented on src/transformer/events/core/notes_viewed.php
> +                   'display' => ['en' => 'Viewed']
hardcoded lang

2024-11-11 17:05 UTC, milt commented on tests/core/note_created/user_created_note/data.json
> +  ],
You don't need to put the course in here.

2024-11-11 17:06 UTC, milt commented on src/transformer/events/core/note_created.php
> +    ],
this should be a function you call from the various note events

2024-11-11 17:08 UTC, milt commented on src/transformer/events/core/note_created.php
> +        'description' => [$lang => $event_object->content],
As with some other things, we should manually check to see if these have HTML tags in them in production that need to be stripped

2024-11-11 17:09 UTC, milt commented on tests/core/note_created/user_created_note/user_created_note_test.php
> +     * @covers ::attempt_submitted
we don't really know what these do, but this one is wrong

2024-11-11 17:10 UTC, milt commented on tests/core/note_updated/user_updated_note/data.json
> +  ],
not needed

2024-11-11 17:11 UTC, milt commented on tests/core/note_updated/user_updated_note/user_updated_note_test.php
> +     * @covers ::attempt_submitted
annotation is wrong

2024-11-11 17:11 UTC, milt commented on tests/core/notes_viewed/user_viewed_notes/data.json
> +  ],
don't need course

2024-11-11 17:11 UTC, milt commented on tests/core/notes_viewed/user_viewed_notes/user_viewed_notes_test.php
> +     * @covers ::attempt_submitted
wrongo

2024-11-11 17:11 UTC, milt commented on tests/core/notes_viewed/user_viewed_notes/user_viewed_notes_test.php
> +     * @covers ::attempt_submitted
wrongo

2024-11-11 17:11 UTC, milt requested changes
See various notes

2024-11-25 17:24 UTC, cliffcaseyyet approved these changes

2024-11-25 17:24 UTC, milt approved these changes

2024-11-25 17:28 UTC, merged